image: gcc

variables:
   GIT_SUBMODULE_STRATEGY: recursive

build:
   stage: build
   script:
      - qmake minergift.pro -spec linux-g++
      - make

test:
   stage: test
   script:
      - cd output
      - LD_LIBRARY_PATH=. ./testminergift
