image: gcc

variables:
   GIT_SUBMODULE_STRATEGY: recursive

stages:
   - build_linux
   - test_linux

mglib:
   stage: build_linux
   script:     
      - qmake mglib/mglib.pro -spec linux-g++
      - make

tests:
   stage: test_linux
   script:
      - qmake test/test.pro -spec linux-g++
      - make
      - cd ../output
      - LD_LIBRARY_PATH=. ./testminergift

ui:
   stage: build_linux
   script:     
      - qmake ui/ui.pro -spec linux-g++
      - make
